name: Import publications from BibTeX

on:
  workflow_dispatch:
  push:
    paths:
      - publications.bib

permissions:
  contents: write

jobs:
  import:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install importer
        run: pip install academic
      - name: Import from BibTeX
        run: academic import --bibtex publications.bib --publication-dir content/publication --overwrite
      - name: Commit changes (if any)
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add content/publication || true
          git commit -m "Import publications from BibTeX" || echo "No changes"
          git push || echo "Nothing to push"
